### ISSUE TITLE
Release v0.2

### ISSUE THREAD

**Issue by regiskuckaertz** [cb372/automagic#4]
Would you mind pushing the latest updates to Maven?

**Comment by regiskuckaertz** [comment]
ping @cb372 😅

**Comment by cb372** [comment]
Weird, I thought I did. I ran `sbt release` and it created a v0.2 tag, but somehow the artifacts didn't make it to Maven Central. Having a look now.

**Comment by cb372** [comment]
@regiskuckaertz Sorry, version 0.2.1 should be on its way to Maven Central now.

**Comment by regiskuckaertz** [comment]
Brilliant! Thank you
